version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      
#
#  Prototype for node ecosystem, needs to be configured
#
#  - package-ecosystem: "npm"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    allow:
#      # allow only production updates
#      - dependency-name: "*"
#        dependency-type: "production"
